### ISSUE TITLE
Issue in examples of README

### ISSUE THREAD

**Issue by jgse** [eiffel-community/eiffel-pythonlib#41]
### Description
The publisher example in README does not work, seems the daemon thread of publisher connection will exit when python program exit. I need to add a call  e.g. time.sleep(1) or wait_close() at the end of the code to make sure event is sent.

**Comment by magnusbaeck** [comment]
Yes, there's clearly a race condition there. I don't think there's a way to wait for a particular event to reach the broker so maybe a sleep would be a reasonable option for such a simple example.

**Comment by t-persson** [comment]
The only way to check for events to be ACK:ed by the broker at the moment is by doing this:

```
UNCONFIRMED = len(PUBLISHER._deliveries) + len(PUBLISHER._nacked_deliveries)
while UNCONFIRMED:
    UNCONFIRMED = len(PUBLISHER._deliveries) + len(PUBLISHER._nacked_deliveries)
    time.sleep(1)
```

But that is not really "legal" in python due to `deliveries` being a "protected" variable.
We should add a method for assisting in this, since we are seeing problems as well and are using the above solution at the moment and update the example.
